# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
#
# Reproduce locally by running:
# ```r
# pak::pak(c("any::pkgdown", "."), dependencies = "Config/Needs/website")
# pkgdown::build_site()
# ```
on:
  push:
    branches: [main, master]
    paths:
      - 'README.Rmd'
      - 'README.md'
      - 'index.Rmd'
      - 'index.md'
      - 'man/**'
      - 'vignettes/**'
      - '_pkgdown.yml'
      - 'pkgdown/**'
      - 'DESCRIPTION'
      - '.Rbuildignore'
      - '.github/**'
  pull_request:
    paths:
      - 'README.Rmd'
      - 'README.md'
      - 'index.Rmd'
      - 'index.md'
      - 'man/**'
      - 'vignettes/**'
      - '_pkgdown.yml'
      - 'pkgdown/**'
      - 'DESCRIPTION'
      - '.Rbuildignore'
      - '.github/**'
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown-quick

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
# Reusable workflow example
  # render-readme-quick: # always run render_readme before building website
  #   uses: ./render_readme_quick.yml
  #   secrets: inherit
    
  pkgdown-quick:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    container: bahadzie/alpine-r:4.3.0
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4

      - name: Temp Fix. https://github.com/peter-evans/create-pull-request/issues/1170
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Compile README.Rmd to keep website up to date
        run: |
          writeLines(
            knitr::knit_expand(
              "README.Rmd",
              packagename = read.dcf("DESCRIPTION", "Package"),
              institution = read.dcf("DESCRIPTION", "Config/Institution"),
              department = read.dcf("DESCRIPTION", "Config/Department"),
              department_url = read.dcf("DESCRIPTION", "Config/DepartmentURL"),
              recon = read.dcf("DESCRIPTION", "Config/Recon"),
              recon_description = read.dcf("DESCRIPTION", "Config/ReconDescription"),
              gh_repo = Sys.getenv("GITHUB_REPOSITORY")
            ),
            "README_expanded.Rmd"
          )
          rmarkdown::render(
            "README_expanded.Rmd",
            output_file = "README.md",
            output_dir = "."
          )
        shell: Rscript {0}

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          # We clean on releases because we want to remove old vignettes,
          # figures, etc. that have been deleted from the `main` branch.
          # But we clean ONLY on releases because we want to be able to keep
          # both the 'stable' and 'dev' websites.
          # Also discussed in https://github.com/r-lib/actions/issues/484
          clean: ${{ github.event_name == 'release' }}
          branch: gh-pages
          folder: docs
