# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
#
# Reproduce locally by running:
# ```r
# pak::pak("any::covr", dependencies = "Config/Needs/coverage")
# covr::codecov(quiet = FALSE)
# ```
on:
  push:
    branches: [main, master]
    paths:
      - 'R/**'
      - 'src/**'
      - 'tests/**'
      - 'inst/**'
      - 'DESCRIPTION'
      - '.github/workflows/test-coverage.yaml'
  pull_request:
    paths:
      - 'R/**'
      - 'src/**'
      - 'tests/**'
      - 'inst/**'
      - 'DESCRIPTION'
      - '.github/workflows/test-coverage.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: test-coverage-quick

jobs:
  test-coverage-quick:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    container: bahadzie/alpine-r:4.3.0
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4

      - name: Temp Fix. https://github.com/peter-evans/create-pull-request/issues/1170
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Test coverage
        run: covr::codecov(quiet = FALSE)
        shell: Rscript {0}
